[env]
_.python.venv = { path = ".venv", create = true }

[settings]
idiomatic_version_file_enable_tools = ["python"]

[tasks.install]
alias = "i"
run = "uv sync --locked --group dev"

[tasks.lint]
run = "uv run --locked ruff check ."

[tasks.test]
run = "uv run --locked pytest --cov=app --cov-report=term-missing"
