"""add linked_asset_id to accounts

Revision ID: 078
Revises: 83291e6a4ecf
Create Date: 2026-08-29 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '078'
down_revision: Union[str, Sequence[str], None] = '83291e6a4ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('linked_asset_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_accounts_linked_asset_id'), 'accounts', ['linked_asset_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'assets', ['linked_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_linked_asset_id'), table_name='accounts')
    op.drop_column('accounts', 'linked_asset_id')
    # ### end Alembic commands ###
