"""savings

Revision ID: 71c948ade3e2
Revises: 014
Create Date: 2026-03-16 23:27:01.627772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c948ade3e2'
down_revision: Union[str, Sequence[str], None] = '014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings', 'target_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('target_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
