"""Add transaction split support

Revision ID: 83291e6a4ecf
Revises: 077
Create Date: 2026-08-29 07:10:57.481935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83291e6a4ecf'
down_revision: Union[str, Sequence[str], None] = '077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_connection_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_agent_knowledge_chunks_embedding'), table_name='agent_knowledge_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_agent_knowledge_chunks_agent_id'), 'agent_knowledge_chunks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_chunks_doc_id'), 'agent_knowledge_chunks', ['doc_id'], unique=False)
    op.drop_index(op.f('uq_agents_one_default_per_user'), table_name='agents', postgresql_where='(is_default = true)')
    op.drop_index(op.f('ix_asset_groups_user_id'), table_name='asset_groups')
    op.alter_column('asset_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_asset_values_asset_date'), table_name='asset_values')
    op.drop_index(op.f('ix_assets_connection_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_group_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_market_price'), table_name='assets', postgresql_where="((valuation_method)::text = 'market_price'::text)")
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ux_assets_user_source_external'), table_name='assets', postgresql_where='(external_id IS NOT NULL)')
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_budgets_recurring_lookup'), table_name='budgets', postgresql_where='(is_recurring = true)')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_category_groups_user_id'), table_name='category_groups')
    op.drop_index(op.f('ix_credit_card_bills_account_id'), table_name='credit_card_bills')
    op.alter_column('fx_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_user_status'), table_name='goals')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_linked_user_id'), table_name='group_members')
    op.drop_constraint(op.f('uq_group_members_group_id_name'), 'group_members', type_='unique')
    op.drop_index(op.f('ix_group_settlements_group_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_group_settlements_receiver_transaction_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_group_settlements_transaction_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_groups_user_id'), table_name='groups')
    op.drop_constraint(op.f('uq_groups_user_id_name'), 'groups', type_='unique')
    op.drop_index(op.f('ix_import_logs_user_id'), table_name='import_logs')
    op.drop_index(op.f('ix_payee_mapping_user_id_target_id'), table_name='payee_mapping')
    op.drop_index(op.f('ix_payee_tax_ids_workspace_kind_value'), table_name='payee_tax_ids')
    op.drop_index(op.f('ix_payees_user_id'), table_name='payees')
    op.drop_index(op.f('uq_payees_workspace_id_lower_name'), table_name='payees')
    op.create_index('uq_payees_workspace_id_lower_name', 'payees', ['workspace_id', sa.literal_column('lower(trim(name))')], unique=True)
    op.alter_column('recurring_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_recurring_transactions_user_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_rules_user_id'), table_name='rules')
    op.drop_index(op.f('ix_transaction_attachments_transaction_id'), table_name='transaction_attachments')
    op.drop_index(op.f('ix_transaction_attachments_user_id'), table_name='transaction_attachments')
    op.drop_index(op.f('ix_transaction_splits_group_member_id'), table_name='transaction_splits')
    op.drop_index(op.f('ix_transaction_splits_transaction_id'), table_name='transaction_splits')
    op.drop_constraint(op.f('uq_transaction_splits_tx_member'), 'transaction_splits', type_='unique')
    op.add_column('transactions', sa.Column('is_split_parent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('transactions', sa.Column('parent_transaction_id', sa.UUID(), nullable=True))
    op.alter_column('transactions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('transactions', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_ignored'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transfer_match'), table_name='transactions', postgresql_where='(transfer_pair_id IS NULL)')
    op.drop_index(op.f('ix_transactions_transfer_pair_id'), table_name='transactions', postgresql_where='(transfer_pair_id IS NOT NULL)')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_parent_transaction_id'), 'transactions', ['parent_transaction_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'transactions', ['parent_transaction_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workspace_members_user'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_workspace'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspaces_kind'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_managed_by_user_id'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspaces_managed_by_user_id'), 'workspaces', ['managed_by_user_id'], unique=False)
    op.create_index(op.f('ix_workspaces_kind'), 'workspaces', ['kind'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user'), 'workspace_members', ['user_id'], unique=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_parent_transaction_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_transfer_pair_id'), 'transactions', ['transfer_pair_id'], unique=False, postgresql_where='(transfer_pair_id IS NOT NULL)')
    op.create_index(op.f('ix_transactions_transfer_match'), 'transactions', ['user_id', 'amount', 'date'], unique=False, postgresql_where='(transfer_pair_id IS NULL)')
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    op.create_index(op.f('ix_transactions_is_ignored'), 'transactions', ['is_ignored'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.alter_column('transactions', 'raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('transactions', 'notes',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('transactions', 'parent_transaction_id')
    op.drop_column('transactions', 'is_split_parent')
    op.create_unique_constraint(op.f('uq_transaction_splits_tx_member'), 'transaction_splits', ['transaction_id', 'group_member_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_transaction_splits_transaction_id'), 'transaction_splits', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_splits_group_member_id'), 'transaction_splits', ['group_member_id'], unique=False)
    op.create_index(op.f('ix_transaction_attachments_user_id'), 'transaction_attachments', ['user_id'], unique=False)
    op.create_index(op.f('ix_transaction_attachments_transaction_id'), 'transaction_attachments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_rules_user_id'), 'rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_user_id'), 'recurring_transactions', ['user_id'], unique=False)
    op.alter_column('recurring_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('uq_payees_workspace_id_lower_name', table_name='payees')
    op.create_index(op.f('uq_payees_workspace_id_lower_name'), 'payees', ['workspace_id', sa.literal_column('lower(btrim(name::text))')], unique=True)
    op.create_index(op.f('ix_payees_user_id'), 'payees', ['user_id'], unique=False)
    op.create_index(op.f('ix_payee_tax_ids_workspace_kind_value'), 'payee_tax_ids', ['workspace_id', 'kind', 'value'], unique=False)
    op.create_index(op.f('ix_payee_mapping_user_id_target_id'), 'payee_mapping', ['user_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_import_logs_user_id'), 'import_logs', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_groups_user_id_name'), 'groups', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_groups_user_id'), 'groups', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_settlements_transaction_id'), 'group_settlements', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_group_settlements_receiver_transaction_id'), 'group_settlements', ['receiver_transaction_id'], unique=False)
    op.create_index(op.f('ix_group_settlements_group_id'), 'group_settlements', ['group_id'], unique=False)
    op.create_unique_constraint(op.f('uq_group_members_group_id_name'), 'group_members', ['group_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_group_members_linked_user_id'), 'group_members', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_goals_user_status'), 'goals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fx_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_credit_card_bills_account_id'), 'credit_card_bills', ['account_id'], unique=False)
    op.create_index(op.f('ix_category_groups_user_id'), 'category_groups', ['user_id'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_index(op.f('ix_budgets_recurring_lookup'), 'budgets', ['user_id', 'category_id', 'month'], unique=False, postgresql_where='(is_recurring = true)')
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.create_index(op.f('ux_assets_user_source_external'), 'assets', ['user_id', 'source', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_index(op.f('ix_assets_market_price'), 'assets', ['valuation_method'], unique=False, postgresql_where="((valuation_method)::text = 'market_price'::text)")
    op.create_index(op.f('ix_assets_group_id'), 'assets', ['group_id'], unique=False)
    op.create_index(op.f('ix_assets_connection_id'), 'assets', ['connection_id'], unique=False)
    op.create_index(op.f('ix_asset_values_asset_date'), 'asset_values', ['asset_id', 'date'], unique=False)
    op.alter_column('asset_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_asset_groups_user_id'), 'asset_groups', ['user_id'], unique=False)
    op.create_index(op.f('uq_agents_one_default_per_user'), 'agents', ['user_id'], unique=True, postgresql_where='(is_default = true)')
    op.drop_index(op.f('ix_agent_knowledge_chunks_doc_id'), table_name='agent_knowledge_chunks')
    op.drop_index(op.f('ix_agent_knowledge_chunks_agent_id'), table_name='agent_knowledge_chunks')
    op.create_index(op.f('ix_agent_knowledge_chunks_embedding'), 'agent_knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_accounts_connection_id'), 'accounts', ['connection_id'], unique=False)
    # ### end Alembic commands ###
