"""add target_amount to savings

Revision ID: d55941f19b40
Revises: 71c948ade3e2
Create Date: 2026-03-19 00:32:09.184729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55941f19b40'
down_revision: Union[str, Sequence[str], None] = '71c948ade3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.drop_column('savings', 'is_recurring')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('savings', 'target_amount')
    # ### end Alembic commands ###
